### ISSUE TITLE
NullPointerException when loading plugin with BungeeCord (latest build)

### ISSUE THREAD

**Issue by ByteExceptionM** [Szczurowsky/MinecraftSentryReporter#37]
**Description:**
After switching from Waterfall to BungeeCord ([latest build](https://ci.md-5.net/job/BungeeCord/lastSuccessfulBuild/artifact/bootstrap/target/BungeeCord.jar)) running on Java 21, I encounter the following exception in the console when starting the BungeeCord proxy:

```
[WARNING] Exception encountered when loading plugin: MinecraftSentryReporter
java.lang.NullPointerException: Cannot invoke "java.util.logging.Logger.addHandler(java.util.logging.Handler)" because the return value of "java.util.logging.Logger.getParent()" is null
    at pl.szczurowsky.minecraftsentryreporter.bungee.MSRBungeePlugin.onEnable(MSRBungeePlugin.java:32)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:266)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:298)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

As a result, the plugin does not report any exceptions to Sentry.

This issue did not occur with Waterfall, and it appears specific to BungeeCord’s handling of the logger setup in the `onEnable` method.

**Comment by Szczurowsky** [comment]
Hi, thanks for reporting the issue. Plugin wasn't updated for quite a long time, so that might be the cause. I will certainly take a look on this problem in free time.
